export enum WebSocketEventType {
    ROOM_CREATED = 'ROOM_CREATED',
    ROOM_DELETED = 'ROOM_DELETED',
    ROOM_UPDATED = 'ROOM_UPDATED',
    ROOM_VOTE = 'ROOM_VOTE',
    USER_CREATED = 'USER_CREATED',
    USER_UPDATED = 'USER_UPDATED',
}
